# Generated by Django 5.2.4 on 2025-07-31 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fraud1',
            options={'managed': True},
        ),
    ]
