# Generated by Django 5.2.4 on 2025-07-31 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_website', '0002_alter_fraud1_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fraud1',
            options={'managed': False},
        ),
    ]
